### ISSUE TITLE
iOS 13 changes trying to fix the code...

### ISSUE THREAD

**Issue by losgranos** [analogcode/Swift-Radio-Pro#147]
A few warning started popping up after updating the Xcode, app still loads but i been trying to troubleshoot them with no luck... any and all help appreciated thanks! - im trying to deploy to iOS 13 since now apple store requires it after april 30th

first the nav bar now is gray can't seem to be able to change it back to black (or any other color)
<a href="https://imgur.com/96xUSxQ"><img src="https://i.imgur.com/96xUSxQ.png" title="source: imgur.com" /></a>

Swift Compiler Warning Group
/Users/dylan/Apps/8Parole/SwiftRadio/StationsViewController.swift:153:30: 'isNetworkActivityIndicatorVisible' was deprecated in iOS 13.0: Provide a custom network activity UI in your app if desired.

/Users/dylan/Apps/8Parole/SwiftRadio/StationsViewController.swift:160:65: 'isNetworkActivityIndicatorVisible' was deprecated in iOS 13.0: Provide a custom network activity UI in your app if desired.

/Users/dylan/Apps/8Parole/SwiftRadio/StationsViewController.swift:374:26: 'dimsBackgroundDuringPresentation' was deprecated in iOS 12.0

/Users/dylan/Apps/8Parole/SwiftRadio/Libraries/FRadioPlayer/FRadioPlayer.swift:525:37: 'timedMetadata' was deprecated in iOS 13.0: Use AVPlayerItemMetadataOutput to obtain timed metadata

/Users/dylan/Apps/8Parole/SwiftRadio/Libraries/Spring/KeyboardLayoutConstraint.swift:63:46: 'keyWindow' was deprecated in iOS 13.0: Should not be used for applications that support multiple scenes as it returns a key window across all connected scenes

/Users/dylan/Apps/8Parole/SwiftRadio/Libraries/Spring/KeyboardLayoutConstraint.swift:92:46: 'keyWindow' was deprecated in iOS 13.0: Should not be used for applications that support multiple scenes as it returns a key window across all connected scenes

**Comment by kajx** [comment]
I can’t even get it to build and run. Still learning code, and uncertain where to start to troubleshoot. If I figure anything out will share the love. 

I had a basic app, now with updates to Swift 5 doesn’t work/comply anymore and was looking for a quick fix.

Kendall

**Comment by fethica** [comment]
@losgranos the app is updated to support iOS 13 and Xcode 11.4, the light navigation bar issue is fixed, you only need to deploy the app using Xcode 11.4 (iOS 13 SDK) you don't have to manually change the `iOS Deployment Target` in the settings, this will drop the support for iOS 10, 11 and 12, and make your app only available for iOS 13.

@kajx app updated, all issues are fixed, just make sure to use the latest Xcode version (11.4).

**Comment by losgranos** [comment]
Ha! thanks for your quick response I guess I should have mentioned I'm working on the CarPlay branch... i can see the master branch works perfectly but the gray bar still shows up on the CarPlay code...  i even try copying and pasting the StationsViewController code to see if that helps, but it doesnt... 

again, thanks so much for this project! i love it!

**Comment by fethica** [comment]
Hey @losgranos all branches updated and in sync with master!

**Comment by Tucker2015** [comment]
> Hey @losgranos all branches are updated and in sync with master!

Is the single station code updated too bud ?

**Comment by losgranos** [comment]
again, thank you so much for help sync it up and it's all good again ...

**Comment by fethica** [comment]
@Tucker2015 the single station code is no longer supported, check the README for more informations.
